### ISSUE TITLE
Could switch from background-image to <img> element for responsiveness

### ISSUE THREAD

**Issue by jhned** [sdras/hero-generator#11]
Hi Sarah! Awesome tool. As a dev who's built a lot of heroes too, I would suggest switching from using background-image to an `<img>` tag and handle the image sizing with `object-fit: cover;`. That way, devs can use `srcset` to pass in lower-resolution versions of the background image.

**Comment by sdras** [comment]
Hey @jhned, you don't necessarily need `srcset` for responsive imagery, [media queries do work](https://timkadlec.com/2012/04/media-query-asset-downloading-results/) for letting the browser know not to download both. Happy to look at tests to the contrary if you have em! Otherwise, closing this out :) Thanks!

**Comment by jhned** [comment]
Yeah, that's a fair point. If I were hooking this up to a CMS, though, I'd prefer `srcset` over media queries because it ends up being cleaner to maintain.
